name: Job Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8 AM UTC (11 AM EAT) every day
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | awk -F. '{print $1}')
        echo "Chrome Version: $CHROME_VERSION"
        
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        echo "Latest ChromeDriver Version: $CHROMEDRIVER_VERSION"
        
        wget -N "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv -f chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        rm chromedriver_linux64.zip
        
        echo "ChromeDriver installation completed"
        chromedriver --version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper and send WhatsApp notification
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
        YOUR_PHONE_NUMBER: ${{ secrets.YOUR_PHONE_NUMBER }}
      run: python src/main.py

    - name: Send WhatsApp notification on failure
      if: failure()
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
        YOUR_PHONE_NUMBER: ${{ secrets.YOUR_PHONE_NUMBER }}
      run: |
        pip install twilio
        python -c "from twilio.rest import Client; client = Client('$TWILIO_ACCOUNT_SID', '$TWILIO_AUTH_TOKEN'); client.messages.create(body='Job Scraper Workflow Failed. Please check the GitHub Actions logs for more information.', from_='whatsapp:$TWILIO_PHONE_NUMBER', to='whatsapp:$YOUR_PHONE_NUMBER')"