name: Job Scraper

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7 AM UTC (10 AM EAT) every day
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print \$3}' | awk -F. '{print \$1}')
          echo "Chrome Version: $CHROME_VERSION"
          
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Latest ChromeDriver Version: $CHROMEDRIVER_VERSION"
          
          wget -N "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv -f chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip
          
          echo "ChromeDriver installation completed"
          chromedriver --version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper and send WhatsApp notification
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
        YOUR_PHONE_NUMBER: ${{ secrets.YOUR_PHONE_NUMBER }}
      run: python src/main.py

    - name: Send email on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.EMAIL_USER}}
        password: ${{secrets.EMAIL_PASS}}
        subject: Job Scraper Workflow Failed
        body: The job scraper workflow has failed. Please check the GitHub Actions logs for more information.
        to: mosesyebei@gmail.com
        from: GitHub Actions